// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotNet_api_service.Models.Data;

#nullable disable

namespace dotNet_api_service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230720114947_VillaFieldChange")]
    partial class VillaFieldChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotNet_api_service.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreateDate = new DateTime(2023, 7, 20, 13, 49, 47, 77, DateTimeKind.Local).AddTicks(5246),
                            Details = "Amazing villa",
                            ImageUrl = "https://www.bailypearl.com/wp-content/uploads/2021/05/villa-la-croix-valmer-facade-2-2-2560x1633.jpg",
                            Name = "SeaSide Villa",
                            Occupancy = 25,
                            Rate = 10.0,
                            SquareFeet = 300,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreateDate = new DateTime(2023, 7, 20, 13, 49, 47, 77, DateTimeKind.Local).AddTicks(5292),
                            Details = "Amazing villa",
                            ImageUrl = "https://www.villas-melrose.fr/wp-content/themes/villas-melrose/assets/images/hp/bg-contact-grand.jpg",
                            Name = "NearForest Villa",
                            Occupancy = 50,
                            Rate = 10.0,
                            SquareFeet = 150,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreateDate = new DateTime(2023, 7, 20, 13, 49, 47, 77, DateTimeKind.Local).AddTicks(5295),
                            Details = "Amazing villa",
                            ImageUrl = "https://www.explorenicecotedazur.com/content/uploads/2021/11/Ephrussi-scaled.jpg",
                            Name = "Sunrise Temple Villa",
                            Occupancy = 25,
                            Rate = 9.0,
                            SquareFeet = 250,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreateDate = new DateTime(2023, 7, 20, 13, 49, 47, 77, DateTimeKind.Local).AddTicks(5297),
                            Details = "Amazing villa",
                            ImageUrl = "https://i.ytimg.com/vi/Fw1IBJxcgc4/maxresdefault.jpg",
                            Name = "Moonlight Elegant Palace",
                            Occupancy = 100,
                            Rate = 10.0,
                            SquareFeet = 280,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreateDate = new DateTime(2023, 7, 20, 13, 49, 47, 77, DateTimeKind.Local).AddTicks(5301),
                            Details = "Amazing villa",
                            ImageUrl = "https://www.marbella-ev.com/wp-content/uploads/2021/03/Most-Luxury-Villla-in-Marbella.jpg",
                            Name = "BellaPlaza Villa",
                            Occupancy = 100,
                            Rate = 9.0,
                            SquareFeet = 450,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "",
                            CreateDate = new DateTime(2023, 7, 20, 13, 49, 47, 77, DateTimeKind.Local).AddTicks(5304),
                            Details = "Amazing villa",
                            ImageUrl = "https://www.villasleona.fr/public/img/big/27099456jpg_6352a08f482b3.jpg",
                            Name = "Paradise Residence Villa",
                            Occupancy = 120,
                            Rate = 8.0,
                            SquareFeet = 500,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
